In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("moviestats.csv")
df.head()

,MovieName,Day,Day_Number,Karnataka,APTG,TamilNadu,Kerala,RestOfIndia,Total
0,RRR,Day 1 [1st Friday],1,14.5,102.50,10.0,4.0,25.0,156.00
1,RRR,Day 2 [1st Saturday],2,12.5,48.50,10.0,3.5,29.5,104.00
2,RRR,Day 3 [1st Sunday],3,11.5,52.50,12.0,4.5,39.5,120.00
3,RRR,Day 4 [1st Monday],4,4.1,29.25,4.4,0.3,21.0,59.05
4,RRR,Day 5 [1st Tuesday],5,3.6,20.50,4.1,0.7,18.4,47.30

In [3]:
# Define a function to handle case statement
def select_col(row):
    if row["MovieName"] == "RRR":
        return row["APTG"]
    elif row["MovieName"] == "Salaar":
        return row["APTG"]
    elif row["MovieName"] == "Baahubali 2":
        return row["APTG"]
    elif row["MovieName"] == "Goat":
        return row["TamilNadu"]
    elif row["MovieName"] == "Leo":
        return row["TamilNadu"]
    elif row["MovieName"] == "Jailer":
        return row["TamilNadu"]
    else:
        return row["RestOfIndia"]
    
df["homecollection"] = df.apply(select_col, axis=1)

In [4]:
df

,MovieName,Day,Day_Number,Karnataka,APTG,TamilNadu,Kerala,RestOfIndia,Total,homecollection
0,RRR,Day 1 [1st Friday],1,14.50,102.50,10.00,4.00,25.00,156.00,102.50
1,RRR,Day 2 [1st Saturday],2,12.50,48.50,10.00,3.50,29.50,104.00,48.50
2,RRR,Day 3 [1st Sunday],3,11.50,52.50,12.00,4.50,39.50,120.00,52.50
3,RRR,Day 4 [1st Monday],4,4.10,29.25,4.40,0.30,21.00,59.05,29.25
4,RRR,Day 5 [1st Tuesday],5,3.60,20.50,4.10,0.70,18.40,47.30,20.50
5,RRR,Day 6 [1st Wednesday],6,3.30,14.80,3.80,1.40,16.00,39.30,14.80
6,RRR,Day 7 [1st Thursday],7,3.10,11.70,3.60,1.20,14.55,34.15,11.70
7,Jawaan,Day 1 [1st Thursday],1,7.10,9.30,7.30,3.50,62.30,89.50,62.30
8,Jawaan,Day 2 [1st Friday],2,4.90,6.30,5.60,1.70,45.00,63.50,45.00
9,Jawaan,Day 3 [1st Saturday],3,8.20,8.90,7.40,2.05,66.45,93.00,66.45
10,Jawaan,Day 4 [1st Sunday],4,8.20,8.50,7.10,2.25,69.75,95.80,69.75
11,Jawaan,Day 5 [1st Monday],5,2.50,2.80,2.30,0.70,30.80,39.10,30.80
12,Jawaan,Day 6 [1st Tuesday],6,2.00,2.20,1.80,0.60,24.20,30.80,24.20
13,Jawaan,Day 7 [1st Wednesday],7,1.80,2.00,1.70,0.50,21.50,27.50,21.50
14,Baahubali 2,Day 1 [1st Friday],1,19.50,57.00,9.25,5.45,60.80,152.00,57.00
15,Baahubali 2,Day 2 [1st Saturday],2,10.00,23.20,11.00,5.80,60.00,110.00,23.20
16,Baahubali 2,Day 3 [1st Sunday],3,9.50,25.50,11.50,6.00,67.50,120.00,25.50
17,Baahubali 2,Day 4 [1st Monday],4,7.50,20.00,11.25,5.75,58.50,103.00,20.00
18,Baahubali 2,Day 5 [1st Tuesday],5,6.50,16.00,9.00,5.50,40.00,77.00,16.00
19,Pushpa,Day 1 [1st Friday],1,6.80,35.50,2.50,4.30,3.70,52.80,3.70
20,Pushpa,Day 2 [1st Saturday],2,4.40,20.70,2.80,5.20,3.30,36.40,3.30
21,Pushpa,Day 3 [1st Sunday],3,3.50,22.30,2.70,6.55,3.70,38.75,3.70
22,Pushpa,Day 4 [1st Monday],4,0.80,11.30,1.05,5.20,1.30,19.65,1.30
23,Pushpa,Day 5 [1st Tuesday],5,0.60,6.40,0.70,4.90,1.00,13.60,1.00
24,Pushpa,Day 6 [1st Wednesday],6,0.45,3.60,0.50,4.15,0.80,9.50,0.80
25,Pushpa,Day 7 [1st Thursday],7,0.30,2.20,0.35,4.05,0.65,7.55,0.65
26,Jailer,Day 1 [1st Thursday],1,11.80,12.50,23.40,5.90,3.00,56.60,23.40
27,Jailer,Day 2 [1st Friday],2,4.05,4.50,16.10,4.80,0.85,30.30,16.10
28,Jailer,Day 3 [1st Saturday],3,6.80,7.05,18.80,6.15,1.40,40.20,18.80
29,Jailer,Day 4 [1st Sunday],4,7.60,9.30,23.90,7.10,1.70,49.60,23.90
30,Jailer,Day 5 [1st Monday],5,4.40,6.00,12.30,4.30,0.60,27.60,12.30
31,Jailer,Day 6 [1st Tuesday],6,7.15,10.50,18.50,5.50,1.25,42.90,18.50
32,Jailer,Day 7 [1st Wednesday],7,2.60,3.65,8.60,2.15,0.50,17.50,8.60
33,Leo,Day 1 [1st Thursday],1,14.10,15.40,30.20,12.00,4.50,76.20,30.20
34,Leo,Day 2 [1st Friday],2,4.10,5.30,22.80,5.85,2.25,40.30,22.80
35,Leo,Day 3 [1st Saturday],3,5.30,5.20,24.10,7.00,3.50,45.10,24.10
36,Leo,Day 4 [1st Sunday],4,4.85,4.15,26.20,7.90,3.70,46.80,26.20
37,Leo,Day 5 [1st Monday],5,3.30,3.05,24.20,7.15,2.40,40.10,24.20
38,Leo,Day 6 [1st Tuesday],6,3.35,4.05,20.15,5.20,3.35,36.10,20.15
39,Leo,Day 7 [1st Wednesday],7,1.35,2.20,8.25,2.10,1.90,15.80,8.25
40,Salaar,Day 1 [1st Friday],1,11.65,67.10,4.90,4.65,18.80,107.10,67.10
41,Salaar,Day 2 [1st Saturday],2,7.25,33.50,4.00,2.65,19.30,66.70,33.50
42,Salaar,Day 3 [1st Sunday],3,6.70,35.60,4.10,2.30,24.80,73.50,35.60
43,Salaar,Day 4 [1st Monday],4,4.65,28.40,2.70,1.80,16.65,54.20,28.40
44,Salaar,Day 5 [1st Tuesday],5,2.20,16.20,1.10,1.05,8.85,29.40,16.20
45,Salaar,Day 6 [1st Wednesday],6,1.30,7.10,1.05,0.80,8.05,18.30,7.10
46,Salaar,Day 7 [1st Thursday],7,1.20,4.00,0.95,0.65,7.50,14.30,4.00
47,Goat,Day 1 [1st Thursday],1,10.00,3.75,29.50,5.75,3.00,52.00,29.50
48,Goat,Day 2 [1st Friday],2,3.25,1.70,21.50,1.50,2.05,30.00,21.50
49,Goat,Day 3 [1st Saturday],3,4.75,2.50,27.00,1.75,3.25,39.25,27.00
50,Goat,Day 4 [1st Sunday],4,4.25,1.85,28.00,1.65,4.00,39.75,28.00
51,Goat,Day 5 [1st Monday],5,0.85,0.65,14.00,0.50,1.25,17.25,14.00

In [5]:
#rajamouli difference

movie_day_1 = df[df["Day_Number"]==1]
movie_day_1.sort_values(by="Total", ascending=False)

,MovieName,Day,Day_Number,Karnataka,APTG,TamilNadu,Kerala,RestOfIndia,Total,homecollection
0,RRR,Day 1 [1st Friday],1,14.50,102.50,10.00,4.00,25.0,156.0,102.5
14,Baahubali 2,Day 1 [1st Friday],1,19.50,57.00,9.25,5.45,60.8,152.0,57.0
40,Salaar,Day 1 [1st Friday],1,11.65,67.10,4.90,4.65,18.8,107.1,67.1
7,Jawaan,Day 1 [1st Thursday],1,7.10,9.30,7.30,3.50,62.3,89.5,62.3
33,Leo,Day 1 [1st Thursday],1,14.10,15.40,30.20,12.00,4.5,76.2,30.2
26,Jailer,Day 1 [1st Thursday],1,11.80,12.50,23.40,5.90,3.0,56.6,23.4
19,Pushpa,Day 1 [1st Friday],1,6.80,35.50,2.50,4.30,3.7,52.8,3.7
47,Goat,Day 1 [1st Thursday],1,10.00,3.75,29.50,5.75,3.0,52.0,29.5

In [6]:
prabhas_data = df[(df["MovieName"] == "Baahubali 2") | (df["MovieName"] == "Salaar")]
prabhas_data

,MovieName,Day,Day_Number,Karnataka,APTG,TamilNadu,Kerala,RestOfIndia,Total,homecollection
14,Baahubali 2,Day 1 [1st Friday],1,19.50,57.0,9.25,5.45,60.80,152.0,57.0
15,Baahubali 2,Day 2 [1st Saturday],2,10.00,23.2,11.00,5.80,60.00,110.0,23.2
16,Baahubali 2,Day 3 [1st Sunday],3,9.50,25.5,11.50,6.00,67.50,120.0,25.5
17,Baahubali 2,Day 4 [1st Monday],4,7.50,20.0,11.25,5.75,58.50,103.0,20.0
18,Baahubali 2,Day 5 [1st Tuesday],5,6.50,16.0,9.00,5.50,40.00,77.0,16.0
40,Salaar,Day 1 [1st Friday],1,11.65,67.1,4.90,4.65,18.80,107.1,67.1
41,Salaar,Day 2 [1st Saturday],2,7.25,33.5,4.00,2.65,19.30,66.7,33.5
42,Salaar,Day 3 [1st Sunday],3,6.70,35.6,4.10,2.30,24.80,73.5,35.6
43,Salaar,Day 4 [1st Monday],4,4.65,28.4,2.70,1.80,16.65,54.2,28.4
44,Salaar,Day 5 [1st Tuesday],5,2.20,16.2,1.10,1.05,8.85,29.4,16.2
45,Salaar,Day 6 [1st Wednesday],6,1.30,7.1,1.05,0.80,8.05,18.3,7.1
46,Salaar,Day 7 [1st Thursday],7,1.20,4.0,0.95,0.65,7.50,14.3,4.0

In [7]:
#Restofindia impact

df["percent_roi"] = df["RestOfIndia"]/df["Total"]
df.sort_values(by="percent_roi", ascending=False)

,MovieName,Day,Day_Number,Karnataka,APTG,TamilNadu,Kerala,RestOfIndia,Total,homecollection,percent_roi
11,Jawaan,Day 5 [1st Monday],5,2.50,2.80,2.30,0.70,30.80,39.10,30.80,0.787724
12,Jawaan,Day 6 [1st Tuesday],6,2.00,2.20,1.80,0.60,24.20,30.80,24.20,0.785714
13,Jawaan,Day 7 [1st Wednesday],7,1.80,2.00,1.70,0.50,21.50,27.50,21.50,0.781818
10,Jawaan,Day 4 [1st Sunday],4,8.20,8.50,7.10,2.25,69.75,95.80,69.75,0.728079
9,Jawaan,Day 3 [1st Saturday],3,8.20,8.90,7.40,2.05,66.45,93.00,66.45,0.714516
8,Jawaan,Day 2 [1st Friday],2,4.90,6.30,5.60,1.70,45.00,63.50,45.00,0.708661
7,Jawaan,Day 1 [1st Thursday],1,7.10,9.30,7.30,3.50,62.30,89.50,62.30,0.696089
17,Baahubali 2,Day 4 [1st Monday],4,7.50,20.00,11.25,5.75,58.50,103.00,20.00,0.567961
16,Baahubali 2,Day 3 [1st Sunday],3,9.50,25.50,11.50,6.00,67.50,120.00,25.50,0.562500
15,Baahubali 2,Day 2 [1st Saturday],2,10.00,23.20,11.00,5.80,60.00,110.00,23.20,0.545455
46,Salaar,Day 7 [1st Thursday],7,1.20,4.00,0.95,0.65,7.50,14.30,4.00,0.524476
18,Baahubali 2,Day 5 [1st Tuesday],5,6.50,16.00,9.00,5.50,40.00,77.00,16.00,0.519481
45,Salaar,Day 6 [1st Wednesday],6,1.30,7.10,1.05,0.80,8.05,18.30,7.10,0.439891
6,RRR,Day 7 [1st Thursday],7,3.10,11.70,3.60,1.20,14.55,34.15,11.70,0.426061
5,RRR,Day 6 [1st Wednesday],6,3.30,14.80,3.80,1.40,16.00,39.30,14.80,0.407125
14,Baahubali 2,Day 1 [1st Friday],1,19.50,57.00,9.25,5.45,60.80,152.00,57.00,0.400000
4,RRR,Day 5 [1st Tuesday],5,3.60,20.50,4.10,0.70,18.40,47.30,20.50,0.389006
3,RRR,Day 4 [1st Monday],4,4.10,29.25,4.40,0.30,21.00,59.05,29.25,0.355631
42,Salaar,Day 3 [1st Sunday],3,6.70,35.60,4.10,2.30,24.80,73.50,35.60,0.337415
2,RRR,Day 3 [1st Sunday],3,11.50,52.50,12.00,4.50,39.50,120.00,52.50,0.329167
43,Salaar,Day 4 [1st Monday],4,4.65,28.40,2.70,1.80,16.65,54.20,28.40,0.307196
44,Salaar,Day 5 [1st Tuesday],5,2.20,16.20,1.10,1.05,8.85,29.40,16.20,0.301020
41,Salaar,Day 2 [1st Saturday],2,7.25,33.50,4.00,2.65,19.30,66.70,33.50,0.289355
1,RRR,Day 2 [1st Saturday],2,12.50,48.50,10.00,3.50,29.50,104.00,48.50,0.283654
40,Salaar,Day 1 [1st Friday],1,11.65,67.10,4.90,4.65,18.80,107.10,67.10,0.175537
0,RRR,Day 1 [1st Friday],1,14.50,102.50,10.00,4.00,25.00,156.00,102.50,0.160256
39,Leo,Day 7 [1st Wednesday],7,1.35,2.20,8.25,2.10,1.90,15.80,8.25,0.120253
50,Goat,Day 4 [1st Sunday],4,4.25,1.85,28.00,1.65,4.00,39.75,28.00,0.100629
21,Pushpa,Day 3 [1st Sunday],3,3.50,22.30,2.70,6.55,3.70,38.75,3.70,0.095484
38,Leo,Day 6 [1st Tuesday],6,3.35,4.05,20.15,5.20,3.35,36.10,20.15,0.092798
20,Pushpa,Day 2 [1st Saturday],2,4.40,20.70,2.80,5.20,3.30,36.40,3.30,0.090659
25,Pushpa,Day 7 [1st Thursday],7,0.30,2.20,0.35,4.05,0.65,7.55,0.65,0.086093
24,Pushpa,Day 6 [1st Wednesday],6,0.45,3.60,0.50,4.15,0.80,9.50,0.80,0.084211
49,Goat,Day 3 [1st Saturday],3,4.75,2.50,27.00,1.75,3.25,39.25,27.00,0.082803
36,Leo,Day 4 [1st Sunday],4,4.85,4.15,26.20,7.90,3.70,46.80,26.20,0.079060
35,Leo,Day 3 [1st Saturday],3,5.30,5.20,24.10,7.00,3.50,45.10,24.10,0.077605
23,Pushpa,Day 5 [1st Tuesday],5,0.60,6.40,0.70,4.90,1.00,13.60,1.00,0.073529
51,Goat,Day 5 [1st Monday],5,0.85,0.65,14.00,0.50,1.25,17.25,14.00,0.072464
19,Pushpa,Day 1 [1st Friday],1,6.80,35.50,2.50,4.30,3.70,52.80,3.70,0.070076
48,Goat,Day 2 [1st Friday],2,3.25,1.70,21.50,1.50,2.05,30.00,21.50,0.068333
22,Pushpa,Day 4 [1st Monday],4,0.80,11.30,1.05,5.20,1.30,19.65,1.30,0.066158
37,Leo,Day 5 [1st Monday],5,3.30,3.05,24.20,7.15,2.40,40.10,24.20,0.059850
33,Leo,Day 1 [1st Thursday],1,14.10,15.40,30.20,12.00,4.50,76.20,30.20,0.059055
47,Goat,Day 1 [1st Thursday],1,10.00,3.75,29.50,5.75,3.00,52.00,29.50,0.057692
34,Leo,Day 2 [1st Friday],2,4.10,5.30,22.80,5.85,2.25,40.30,22.80,0.055831
26,Jailer,Day 1 [1st Thursday],1,11.80,12.50,23.40,5.90,3.00,56.60,23.40,0.053004
28,Jailer,Day 3 [1st Saturday],3,6.80,7.05,18.80,6.15,1.40,40.20,18.80,0.034826
29,Jailer,Day 4 [1st Sunday],4,7.60,9.30,23.90,7.10,1.70,49.60,23.90,0.034274
31,Jailer,Day 6 [1st Tuesday],6,7.15,10.50,18.50,5.50,1.25,42.90,18.50,0.029138
32,Jailer,Day 7 [1st Wednesday],7,2.60,3.65,8.60,2.15,0.50,17.50,8.60,0.028571
27,Jailer,Day 2 [1st Friday],2,4.05,4.50,16.10,4.80,0.85,30.30,16.10,0.028053
30,Jailer,Day 5 [1st Monday],5,4.40,6.00,12.30,4.30,0.60,27.60,12.30,0.021739

In [8]:
df["previousdaytotal"] = df.groupby("MovieName")["Total"].shift(1)
df["percent_chng"] = (df["Total"] - df["previousdaytotal"]) / df["previousdaytotal"]
df

,MovieName,Day,Day_Number,Karnataka,APTG,TamilNadu,Kerala,RestOfIndia,Total,homecollection,percent_roi,previousdaytotal,percent_chng
0,RRR,Day 1 [1st Friday],1,14.50,102.50,10.00,4.00,25.00,156.00,102.50,0.160256,NaN,NaN
1,RRR,Day 2 [1st Saturday],2,12.50,48.50,10.00,3.50,29.50,104.00,48.50,0.283654,156.00,-0.333333
2,RRR,Day 3 [1st Sunday],3,11.50,52.50,12.00,4.50,39.50,120.00,52.50,0.329167,104.00,0.153846
3,RRR,Day 4 [1st Monday],4,4.10,29.25,4.40,0.30,21.00,59.05,29.25,0.355631,120.00,-0.507917
4,RRR,Day 5 [1st Tuesday],5,3.60,20.50,4.10,0.70,18.40,47.30,20.50,0.389006,59.05,-0.198984
5,RRR,Day 6 [1st Wednesday],6,3.30,14.80,3.80,1.40,16.00,39.30,14.80,0.407125,47.30,-0.169133
6,RRR,Day 7 [1st Thursday],7,3.10,11.70,3.60,1.20,14.55,34.15,11.70,0.426061,39.30,-0.131043
7,Jawaan,Day 1 [1st Thursday],1,7.10,9.30,7.30,3.50,62.30,89.50,62.30,0.696089,NaN,NaN
8,Jawaan,Day 2 [1st Friday],2,4.90,6.30,5.60,1.70,45.00,63.50,45.00,0.708661,89.50,-0.290503
9,Jawaan,Day 3 [1st Saturday],3,8.20,8.90,7.40,2.05,66.45,93.00,66.45,0.714516,63.50,0.464567
10,Jawaan,Day 4 [1st Sunday],4,8.20,8.50,7.10,2.25,69.75,95.80,69.75,0.728079,93.00,0.030108
11,Jawaan,Day 5 [1st Monday],5,2.50,2.80,2.30,0.70,30.80,39.10,30.80,0.787724,95.80,-0.591858
12,Jawaan,Day 6 [1st Tuesday],6,2.00,2.20,1.80,0.60,24.20,30.80,24.20,0.785714,39.10,-0.212276
13,Jawaan,Day 7 [1st Wednesday],7,1.80,2.00,1.70,0.50,21.50,27.50,21.50,0.781818,30.80,-0.107143
14,Baahubali 2,Day 1 [1st Friday],1,19.50,57.00,9.25,5.45,60.80,152.00,57.00,0.400000,NaN,NaN
15,Baahubali 2,Day 2 [1st Saturday],2,10.00,23.20,11.00,5.80,60.00,110.00,23.20,0.545455,152.00,-0.276316
16,Baahubali 2,Day 3 [1st Sunday],3,9.50,25.50,11.50,6.00,67.50,120.00,25.50,0.562500,110.00,0.090909
17,Baahubali 2,Day 4 [1st Monday],4,7.50,20.00,11.25,5.75,58.50,103.00,20.00,0.567961,120.00,-0.141667
18,Baahubali 2,Day 5 [1st Tuesday],5,6.50,16.00,9.00,5.50,40.00,77.00,16.00,0.519481,103.00,-0.252427
19,Pushpa,Day 1 [1st Friday],1,6.80,35.50,2.50,4.30,3.70,52.80,3.70,0.070076,NaN,NaN
20,Pushpa,Day 2 [1st Saturday],2,4.40,20.70,2.80,5.20,3.30,36.40,3.30,0.090659,52.80,-0.310606
21,Pushpa,Day 3 [1st Sunday],3,3.50,22.30,2.70,6.55,3.70,38.75,3.70,0.095484,36.40,0.064560
22,Pushpa,Day 4 [1st Monday],4,0.80,11.30,1.05,5.20,1.30,19.65,1.30,0.066158,38.75,-0.492903
23,Pushpa,Day 5 [1st Tuesday],5,0.60,6.40,0.70,4.90,1.00,13.60,1.00,0.073529,19.65,-0.307888
24,Pushpa,Day 6 [1st Wednesday],6,0.45,3.60,0.50,4.15,0.80,9.50,0.80,0.084211,13.60,-0.301471
25,Pushpa,Day 7 [1st Thursday],7,0.30,2.20,0.35,4.05,0.65,7.55,0.65,0.086093,9.50,-0.205263
26,Jailer,Day 1 [1st Thursday],1,11.80,12.50,23.40,5.90,3.00,56.60,23.40,0.053004,NaN,NaN
27,Jailer,Day 2 [1st Friday],2,4.05,4.50,16.10,4.80,0.85,30.30,16.10,0.028053,56.60,-0.464664
28,Jailer,Day 3 [1st Saturday],3,6.80,7.05,18.80,6.15,1.40,40.20,18.80,0.034826,30.30,0.326733
29,Jailer,Day 4 [1st Sunday],4,7.60,9.30,23.90,7.10,1.70,49.60,23.90,0.034274,40.20,0.233831
30,Jailer,Day 5 [1st Monday],5,4.40,6.00,12.30,4.30,0.60,27.60,12.30,0.021739,49.60,-0.443548
31,Jailer,Day 6 [1st Tuesday],6,7.15,10.50,18.50,5.50,1.25,42.90,18.50,0.029138,27.60,0.554348
32,Jailer,Day 7 [1st Wednesday],7,2.60,3.65,8.60,2.15,0.50,17.50,8.60,0.028571,42.90,-0.592075
33,Leo,Day 1 [1st Thursday],1,14.10,15.40,30.20,12.00,4.50,76.20,30.20,0.059055,NaN,NaN
34,Leo,Day 2 [1st Friday],2,4.10,5.30,22.80,5.85,2.25,40.30,22.80,0.055831,76.20,-0.471129
35,Leo,Day 3 [1st Saturday],3,5.30,5.20,24.10,7.00,3.50,45.10,24.10,0.077605,40.30,0.119107
36,Leo,Day 4 [1st Sunday],4,4.85,4.15,26.20,7.90,3.70,46.80,26.20,0.079060,45.10,0.037694
37,Leo,Day 5 [1st Monday],5,3.30,3.05,24.20,7.15,2.40,40.10,24.20,0.059850,46.80,-0.143162
38,Leo,Day 6 [1st Tuesday],6,3.35,4.05,20.15,5.20,3.35,36.10,20.15,0.092798,40.10,-0.099751
39,Leo,Day 7 [1st Wednesday],7,1.35,2.20,8.25,2.10,1.90,15.80,8.25,0.120253,36.10,-0.562327
40,Salaar,Day 1 [1st Friday],1,11.65,67.10,4.90,4.65,18.80,107.10,67.10,0.175537,NaN,NaN
41,Salaar,Day 2 [1st Saturday],2,7.25,33.50,4.00,2.65,19.30,66.70,33.50,0.289355,107.10,-0.377218
42,Salaar,Day 3 [1st Sunday],3,6.70,35.60,4.10,2.30,24.80,73.50,35.60,0.337415,66.70,0.101949
43,Salaar,Day 4 [1st Monday],4,4.65,28.40,2.70,1.80,16.65,54.20,28.40,0.307196,73.50,-0.262585
44,Salaar,Day 5 [1st Tuesday],5,2.20,16.20,1.10,1.05,8.85,29.40,16.20,0.301020,54.20,-0.457565
45,Salaar,Day 6 [1st Wednesday],6,1.30,7.10,1.05,0.80,8.05,18.30,7.10,0.439891,29.40,-0.377551
46,Salaar,Day 7 [1st Thursday],7,1.20,4.00,0.95,0.65,7.50,14.30,4.00,0.524476,18.30,-0.218579
47,Goat,Day 1 [1st Thursday],1,10.00,3.75,29.50,5.75,3.00,52.00,29.50,0.057692,NaN,NaN
48,Goat,Day 2 [1st Friday],2,3.25,1.70,21.50,1.50,2.05,30.00,21.50,0.068333,52.00,-0.423077
49,Goat,Day 3 [1st Saturday],3,4.75,2.50,27.00,1.75,3.25,39.25,27.00,0.082803,30.00,0.308333
50,Goat,Day 4 [1st Sunday],4,4.25,1.85,28.00,1.65,4.00,39.75,28.00,0.100629,39.25,0.012739
51,Goat,Day 5 [1st Monday],5,0.85,0.65,14.00,0.50,1.25,17.25,14.00,0.072464,39.75,-0.566038

In [10]:
#home total

homedata = df.groupby("MovieName")["homecollection"].sum().reset_index()
homedata["rank"] = homedata["homecollection"].rank(method = 'dense', ascending=False)
homedata.sort_values(by='rank')

     MovieName  homecollection  rank
3       Jawaan          320.00   1.0
6          RRR          279.75   2.0
7       Salaar          191.90   3.0
4          Leo          155.90   4.0
0  Baahubali 2          141.70   5.0
2       Jailer          121.60   6.0
1         Goat          120.00   7.0
5       Pushpa           14.45   8.0

In [11]:
#vijay vs rajni

leojailerdata = df[(df["MovieName"] == "Jailer") | (df["MovieName"] == "Leo")]
leojailerdata.groupby("MovieName")["Total"].sum().reset_index()

  MovieName  Total
0    Jailer  264.7
1       Leo  300.4